// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "../../";

export type ExternalType1 = string;

export const ExternalType1 = autoguard.guards.String;

export type ExternalType2 = string;

export const ExternalType2 = autoguard.guards.String;

export type ExternalType3 = string;

export const ExternalType3 = autoguard.guards.String;

export namespace Autoguard {
	export type Guards = {
		"ExternalType1": ExternalType1,
		"ExternalType2": ExternalType2,
		"ExternalType3": ExternalType3
	};

	export const Guards = {
		"ExternalType1": ExternalType1,
		"ExternalType2": ExternalType2,
		"ExternalType3": ExternalType3
	};

	export type Routes = {
	};

	export const Client = (options?: Partial<{ urlPrefix: string }>): Routes => ({
	});

	export const Server = (routes: Routes, options?: Partial<{}>): autoguard.api.RequestListener => {
		let endpoints = new Array<autoguard.api.Endpoint>();
		return (request, response) => autoguard.api.route(endpoints, request, response);
	};
};
