// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "../../";

export type ExternalType1 = string;

export const ExternalType1 = autoguard.String;

export type ExternalType2 = string;

export const ExternalType2 = autoguard.String;

export type ExternalType3 = string;

export const ExternalType3 = autoguard.String;

export type Autoguard = {
	"ExternalType1": ExternalType1,
	"ExternalType2": ExternalType2,
	"ExternalType3": ExternalType3
};

export const Autoguard = {
	"ExternalType1": ExternalType1,
	"ExternalType2": ExternalType2,
	"ExternalType3": ExternalType3
};
