// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "../../../";
import * as shared from "./index";

export const makeClient = (options?: Partial<{
	urlPrefix: string,
	requestHandler: autoguard.api.RequestHandler
}>): autoguard.api.Client<shared.Autoguard.Requests, shared.Autoguard.Responses> => ({
	"POST:/<component>/": async (request) => {
		let guard = shared.Autoguard.Requests["POST:/<component>/"];
		guard.as(request, "CLIENT:request");
		let method = "POST";
		let components = new Array<string>();
		components.push(String(request.options["component"]));
		components.push(decodeURIComponent(""));
		let parameters = autoguard.api.extractKeyValuePairs(request.options ?? {}, ["component"]);
		let headers = autoguard.api.extractKeyValuePairs(request.headers ?? {});
		let payload = autoguard.api.serializePayload(request.payload);
		let requestHandler = options?.requestHandler ?? autoguard.api.xhr;
		let raw = await requestHandler({ method, components, parameters, headers, payload }, options?.urlPrefix);
		{
			let status = raw.status;
			let headers = autoguard.api.combineKeyValuePairs(raw.headers);
			headers["header"] = autoguard.api.getStringOption(raw.headers, "header");
			let payload = await autoguard.api.deserializePayload(raw.payload);
			let guard = shared.Autoguard.Responses["POST:/<component>/"];
			let response = guard.as({ status, headers, payload }, "CLIENT:response");
			return new autoguard.api.ServerResponse(response);
		}
	},
});
