// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "../../../dist/lib-shared";

export namespace Autoguard {
	export const Guards = {};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {
		"plain": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"ca": autoguard.guards.String,
					"pa": autoguard.guards.String
				}, {
					"cb": autoguard.guards.String,
					"cc": autoguard.guards.Array.of(autoguard.guards.String),
					"pb": autoguard.guards.String,
					"pc": autoguard.guards.Array.of(autoguard.guards.String)
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"ha": autoguard.guards.String
				}, {
					"hb": autoguard.guards.String,
					"hc": autoguard.guards.Array.of(autoguard.guards.String)
				}),
				autoguard.api.Headers
			)
		}, {
			"payload": autoguard.api.Binary
		}),
		"json": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"ca": autoguard.guards.Number,
					"pa": autoguard.guards.Number
				}, {
					"cb": autoguard.guards.Number,
					"cc": autoguard.guards.Array.of(autoguard.guards.Number),
					"pb": autoguard.guards.Number,
					"pc": autoguard.guards.Array.of(autoguard.guards.Number)
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"ha": autoguard.guards.Number
				}, {
					"hb": autoguard.guards.Number,
					"hc": autoguard.guards.Array.of(autoguard.guards.Number)
				}),
				autoguard.api.Headers
			)
		}, {
			"payload": autoguard.api.Binary
		})
	};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {
		"plain": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"ha": autoguard.guards.String
				}, {
					"hb": autoguard.guards.String,
					"hc": autoguard.guards.Array.of(autoguard.guards.String)
				}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Integer,
			"payload": autoguard.api.Binary
		}),
		"json": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"ha": autoguard.guards.Number
				}, {
					"hb": autoguard.guards.Number,
					"hc": autoguard.guards.Array.of(autoguard.guards.Number)
				}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Integer,
			"payload": autoguard.api.Binary
		})
	};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
