// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "../../../";
import * as shared from "./shared";

export const Client = (options?: Partial<{ urlPrefix: string }>): shared.Autoguard.Routes => ({
});
