// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "../../../dist/lib-shared";

export const Object: autoguard.serialization.MessageGuard<Object> = autoguard.guards.Object.of({
	"object_id": autoguard.guards.String,
	"name": autoguard.guards.String
}, {});

export type Object = autoguard.guards.Object<{
	"object_id": autoguard.guards.String,
	"name": autoguard.guards.String
}, {}>;

export namespace Autoguard {
	export const Guards = {
		"Object": autoguard.guards.Reference.of(() => Object)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {
		"GET:/": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"POST:/": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/one": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/one/": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/one/two": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_component>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"dynamic_component": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_plain_component>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"dynamic_plain_component": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_boolean_component>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"dynamic_boolean_component": autoguard.guards.Boolean
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_number_component>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"dynamic_number_component": autoguard.guards.Number
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_string_component>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"dynamic_string_component": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_component_one>/<dynamic_component_two>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"dynamic_component_one": autoguard.guards.String,
					"dynamic_component_two": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<quoted key>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"quoted key": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/%22r%C3%A4ksm%C3%B6rg%C3%A5s%22": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters01": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters02": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_boolean_parameter": autoguard.guards.Boolean
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters03": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_boolean_parameter": autoguard.guards.Boolean
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters04": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_number_parameter": autoguard.guards.Number
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters05": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_number_parameter": autoguard.guards.Number
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters06": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_string_parameter": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters07": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_string_parameter": autoguard.guards.String
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters08": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"parameter_one": autoguard.guards.String,
					"parameter_two": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters09": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"quoted key": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters10": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_parameter": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters11": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_parameter": autoguard.guards.String
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters12": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_plain_parameter": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters13": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_plain_parameter": autoguard.guards.String
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query02": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_boolean_parameter": autoguard.guards.Boolean
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query03": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_boolean_parameter": autoguard.guards.Boolean
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query04": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_number_parameter": autoguard.guards.Number
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query05": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_number_parameter": autoguard.guards.Number
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query06": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_string_parameter": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query07": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_string_parameter": autoguard.guards.String
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query08": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"parameter_one": autoguard.guards.String,
					"parameter_two": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query09": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"quoted key": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query10": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_parameter": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query11": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_parameter": autoguard.guards.String
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query12": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_plain_parameter": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query13": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_plain_parameter": autoguard.guards.String
				}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers01": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers02": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_boolean_request_header": autoguard.guards.Boolean
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers03": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_boolean_request_header": autoguard.guards.Boolean
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers04": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_number_request_header": autoguard.guards.Number
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers05": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_number_request_header": autoguard.guards.Number
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers06": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_string_request_header": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers07": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_string_request_header": autoguard.guards.String
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers08": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"request_header_one": autoguard.guards.String,
					"request_header_two": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers09": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"quoted key": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers10": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_request_header": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers11": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_request_header": autoguard.guards.String
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers12": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_plain_request_header": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers13": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_plain_request_header": autoguard.guards.String
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers01": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers02": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers03": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers04": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers05": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers06": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers07": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers08": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers09": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers10": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers11": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers12": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers13": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_payload01": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"required_request_member": autoguard.guards.String
			}, {})
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/request_payload02": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({}, {
				"optional_request_member": autoguard.guards.String
			})
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/response_payload01": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_payload02": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/full_example": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"parameter": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"request_header": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.guards.Object.of({
				"in_request_payload": autoguard.guards.String
			}, {})
		}, {}),
		"GET:/reference": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/binary_request": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/binary_response": autoguard.guards.Object.of({}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/number/<number>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"number": autoguard.guards.Number
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		})
	};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {
		"GET:/": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"POST:/": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/one": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/one/": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/one/two": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_component>": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_plain_component>": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_boolean_component>": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_number_component>": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_string_component>": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<dynamic_component_one>/<dynamic_component_two>": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/<quoted key>": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/%22r%C3%A4ksm%C3%B6rg%C3%A5s%22": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters01": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters02": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters03": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters04": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters05": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters06": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters07": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters08": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters09": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters10": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters11": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters12": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/parameters13": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query02": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query03": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query04": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query05": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query06": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query07": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query08": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query09": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query10": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query11": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query12": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/query13": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers01": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers02": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers03": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers04": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers05": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers06": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers07": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers08": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers09": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers10": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers11": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers12": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_headers13": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers01": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers02": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_boolean_response_header": autoguard.guards.Boolean
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Integer,
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers03": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_boolean_response_header": autoguard.guards.Boolean
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers04": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_number_response_header": autoguard.guards.Number
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Integer,
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers05": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_number_response_header": autoguard.guards.Number
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers06": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_string_response_header": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Integer,
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers07": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_string_response_header": autoguard.guards.String
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers08": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"response_header_one": autoguard.guards.String,
					"response_header_two": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Integer,
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers09": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"quoted key": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Integer,
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers10": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_response_header": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Integer,
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers11": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_response_header": autoguard.guards.String
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers12": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"required_plain_response_header": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Integer,
			"payload": autoguard.api.Binary
		}),
		"GET:/response_headers13": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {
					"optional_plain_response_header": autoguard.guards.String
				}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_payload01": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/request_payload02": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/response_payload01": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"required_request_member": autoguard.guards.String
			}, {})
		}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/response_payload02": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({}, {
				"optional_request_member": autoguard.guards.String
			})
		}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/full_example": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"response_header": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.guards.Object.of({
				"in_response_payload": autoguard.guards.String
			}, {})
		}, {
			"status": autoguard.guards.Integer
		}),
		"GET:/reference": autoguard.guards.Object.of({
			"payload": autoguard.guards.Reference.of(() => Object)
		}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/binary_request": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/binary_response": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/number/<number>": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Integer,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		})
	};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
