// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "../../../";
import * as shared from "./index";

export const makeServer = (routes: autoguard.api.Server<shared.Autoguard.Requests, shared.Autoguard.Responses>, options?: Partial<{}>): autoguard.api.RequestListener => {
	let endpoints = new Array<autoguard.api.Endpoint>();
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "POST";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["POST:/"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["POST:/"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["POST:/"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("one")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/one"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/one"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/one"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("one")]);
		components.push(["", decodeURIComponent("")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/one/"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/one/"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/one/"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("one")]);
		components.push(["", decodeURIComponent("two")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/one/two"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/one/two"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/one/two"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["dynamic_boolean_component", raw.components[0]]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["dynamic_boolean_component"] = autoguard.api.getBooleanOption(components, "dynamic_boolean_component");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/<dynamic_boolean_component>"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/<dynamic_boolean_component>"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/<dynamic_boolean_component>"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["dynamic_number_component", raw.components[0]]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["dynamic_number_component"] = autoguard.api.getNumberOption(components, "dynamic_number_component");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/<dynamic_number_component>"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/<dynamic_number_component>"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/<dynamic_number_component>"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["dynamic_string_component", raw.components[0]]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["dynamic_string_component"] = autoguard.api.getStringOption(components, "dynamic_string_component");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/<dynamic_string_component>"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/<dynamic_string_component>"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/<dynamic_string_component>"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["dynamic_component_one", raw.components[0]]);
		components.push(["dynamic_component_two", raw.components[1]]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["dynamic_component_one"] = autoguard.api.getStringOption(components, "dynamic_component_one");
				options["dynamic_component_two"] = autoguard.api.getStringOption(components, "dynamic_component_two");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/<dynamic_component_one>/<dynamic_component_two>"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/<dynamic_component_one>/<dynamic_component_two>"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/<dynamic_component_one>/<dynamic_component_two>"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["quoted key", raw.components[0]]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["quoted key"] = autoguard.api.getStringOption(components, "quoted key");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/<quoted key>"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/<quoted key>"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/<quoted key>"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("%22r%C3%A4ksm%C3%B6rg%C3%A5s%22")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/%22r%C3%A4ksm%C3%B6rg%C3%A5s%22"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/%22r%C3%A4ksm%C3%B6rg%C3%A5s%22"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/%22r%C3%A4ksm%C3%B6rg%C3%A5s%22"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("parameters01")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/parameters01"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/parameters01"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/parameters01"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("parameters02")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["required_boolean_parameter"] = autoguard.api.getBooleanOption(raw.parameters, "required_boolean_parameter");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/parameters02"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/parameters02"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/parameters02"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("parameters03")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["optional_boolean_parameter"] = autoguard.api.getBooleanOption(raw.parameters, "optional_boolean_parameter");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/parameters03"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/parameters03"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/parameters03"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("parameters04")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["required_number_parameter"] = autoguard.api.getNumberOption(raw.parameters, "required_number_parameter");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/parameters04"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/parameters04"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/parameters04"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("parameters05")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["optional_number_parameter"] = autoguard.api.getNumberOption(raw.parameters, "optional_number_parameter");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/parameters05"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/parameters05"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/parameters05"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("parameters06")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["required_string_parameter"] = autoguard.api.getStringOption(raw.parameters, "required_string_parameter");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/parameters06"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/parameters06"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/parameters06"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("parameters07")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["optional_string_parameter"] = autoguard.api.getStringOption(raw.parameters, "optional_string_parameter");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/parameters07"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/parameters07"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/parameters07"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("parameters08")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["parameter_one"] = autoguard.api.getStringOption(raw.parameters, "parameter_one");
				options["parameter_two"] = autoguard.api.getStringOption(raw.parameters, "parameter_two");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/parameters08"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/parameters08"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/parameters08"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("parameters09")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["quoted key"] = autoguard.api.getStringOption(raw.parameters, "quoted key");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/parameters09"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/parameters09"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/parameters09"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_headers01")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_headers01"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_headers01"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_headers01"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_headers02")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				headers["required_boolean_request_header"] = autoguard.api.getBooleanOption(raw.headers, "required_boolean_request_header");
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_headers02"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_headers02"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_headers02"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_headers03")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				headers["optional_boolean_request_header"] = autoguard.api.getBooleanOption(raw.headers, "optional_boolean_request_header");
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_headers03"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_headers03"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_headers03"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_headers04")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				headers["required_number_request_header"] = autoguard.api.getNumberOption(raw.headers, "required_number_request_header");
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_headers04"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_headers04"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_headers04"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_headers05")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				headers["optional_number_request_header"] = autoguard.api.getNumberOption(raw.headers, "optional_number_request_header");
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_headers05"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_headers05"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_headers05"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_headers06")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				headers["required_string_request_header"] = autoguard.api.getStringOption(raw.headers, "required_string_request_header");
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_headers06"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_headers06"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_headers06"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_headers07")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				headers["optional_string_request_header"] = autoguard.api.getStringOption(raw.headers, "optional_string_request_header");
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_headers07"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_headers07"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_headers07"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_headers08")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				headers["request_header_one"] = autoguard.api.getStringOption(raw.headers, "request_header_one");
				headers["request_header_two"] = autoguard.api.getStringOption(raw.headers, "request_header_two");
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_headers08"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_headers08"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_headers08"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_headers09")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				headers["quoted key"] = autoguard.api.getStringOption(raw.headers, "quoted key");
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_headers09"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_headers09"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_headers09"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_headers01")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_headers01"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_headers01"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_headers01"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_headers02")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_headers02"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_headers02"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_headers02"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_headers03")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_headers03"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_headers03"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_headers03"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_headers04")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_headers04"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_headers04"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_headers04"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_headers05")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_headers05"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_headers05"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_headers05"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_headers06")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_headers06"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_headers06"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_headers06"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_headers07")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_headers07"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_headers07"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_headers07"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_headers08")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_headers08"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_headers08"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_headers08"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_headers09")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_headers09"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_headers09"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_headers09"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_payload01")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_payload01"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_payload01"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_payload01"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("request_payload02")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/request_payload02"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/request_payload02"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/request_payload02"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_payload01")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_payload01"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_payload01"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_payload01"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("response_payload02")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/response_payload02"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/response_payload02"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/response_payload02"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("full_example")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["parameter"] = autoguard.api.getStringOption(raw.parameters, "parameter");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				headers["request_header"] = autoguard.api.getStringOption(raw.headers, "request_header");
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/full_example"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/full_example"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/full_example"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("reference")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/reference"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/reference"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/reference"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("binary_request")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = raw.payload;
				let guard = shared.Autoguard.Requests["GET:/binary_request"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/binary_request"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/binary_request"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("binary_response")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/binary_response"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/binary_response"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/binary_response"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	endpoints.push((raw) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("number")]);
		components.push(["number", raw.components[1]]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			prepareRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["number"] = autoguard.api.getNumberOption(components, "number");
				options["number"] = autoguard.api.getNumberOption(raw.parameters, "number");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/number/<number>"];
				let request = guard.as({ options, headers, payload }, "SERVER:request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/number/<number>"](new autoguard.api.ClientRequest(request));
						let guard = shared.Autoguard.Responses["GET:/number/<number>"];
						guard.as(response, "SERVER:response");
						return response;
					}
				};
			}
		};
	});
	return (request, response) => autoguard.api.route(endpoints, request, response);
};
