// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "../../../";

export namespace Autoguard {
	export type Guards = {};

	export const Guards = {};

	export type Routes = {
		"GET:/": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"POST:/": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/one": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/one/": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/one/two": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/<dynamic_boolean_component>": (request: {
			"options": {
				"dynamic_boolean_component": boolean
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/<dynamic_number_component>": (request: {
			"options": {
				"dynamic_number_component": number
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/<dynamic_string_component>": (request: {
			"options": {
				"dynamic_string_component": string
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/<dynamic_component_one>/<dynamic_component_two>": (request: {
			"options": {
				"dynamic_component_one": string,
				"dynamic_component_two": string
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/parameters01": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/parameters02": (request: {
			"options": {
				"required_boolean_parameter": boolean
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/parameters03": (request: {
			"options"?: {
				"optional_boolean_parameter"?: boolean
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/parameters04": (request: {
			"options": {
				"required_number_parameter": number
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/parameters05": (request: {
			"options"?: {
				"optional_number_parameter"?: number
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/parameters06": (request: {
			"options": {
				"required_string_parameter": string
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/parameters07": (request: {
			"options"?: {
				"optional_string_parameter"?: string
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/parameters08": (request: {
			"options": {
				"parameter_one": string,
				"parameter_two": string
			},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/request_headers01": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/request_headers02": (request: {
			"options"?: {},
			"headers": {
				"required_boolean_request_header": boolean
			},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/request_headers03": (request: {
			"options"?: {},
			"headers"?: {
				"optional_boolean_request_header"?: boolean
			},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/request_headers04": (request: {
			"options"?: {},
			"headers": {
				"required_number_request_header": number
			},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/request_headers05": (request: {
			"options"?: {},
			"headers"?: {
				"optional_number_request_header"?: number
			},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/request_headers06": (request: {
			"options"?: {},
			"headers": {
				"required_string_request_header": string
			},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/request_headers07": (request: {
			"options"?: {},
			"headers"?: {
				"optional_string_request_header"?: string
			},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/request_headers08": (request: {
			"options"?: {},
			"headers": {
				"request_header_one": string,
				"request_header_two": string
			},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/response_headers01": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/response_headers02": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers": {
				"required_boolean_response_header": boolean
			},
			"payload"?: undefined
		}>;
		"GET:/response_headers03": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {
				"optional_boolean_response_header"?: boolean
			},
			"payload"?: undefined
		}>;
		"GET:/response_headers04": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers": {
				"required_number_response_header": number
			},
			"payload"?: undefined
		}>;
		"GET:/response_headers05": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {
				"optional_number_response_header"?: number
			},
			"payload"?: undefined
		}>;
		"GET:/response_headers06": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers": {
				"required_string_response_header": string
			},
			"payload"?: undefined
		}>;
		"GET:/response_headers07": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {
				"optional_string_response_header"?: string
			},
			"payload"?: undefined
		}>;
		"GET:/response_headers08": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers": {
				"response_header_one": string,
				"response_header_two": string
			},
			"payload"?: undefined
		}>;
		"GET:/request_payload01": (request: {
			"options"?: {},
			"headers"?: {},
			"payload": {
				"required_request_member": string
			}
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/request_payload02": (request: {
			"options"?: {},
			"headers"?: {},
			"payload": {
				"optional_request_member"?: string
			}
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload"?: undefined
		}>;
		"GET:/response_payload01": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload": {
				"required_request_member": string
			}
		}>;
		"GET:/response_payload02": (request: {
			"options"?: {},
			"headers"?: {},
			"payload"?: undefined
		}) => Promise<{
			"status"?: number,
			"headers"?: {},
			"payload": {
				"optional_request_member"?: string
			}
		}>;
		"GET:/full_example": (request: {
			"options": {
				"parameter": string
			},
			"headers": {
				"request_header": string
			},
			"payload": {
				"in_request_payload": string
			}
		}) => Promise<{
			"status"?: number,
			"headers": {
				"response_header": string
			},
			"payload": {
				"in_response_payload": string
			}
		}>;
	};
};
